{% set name = "apsw" %}
{% set version = "3.51.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/rogerbinns/apsw/releases/download/{{ version }}/{{ name }}-{{ version }}.zip
  sha256: b3820bdbc84580c72f6633674ca3dd6a59542c851dc120c0dedf4de7d15ee183

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - apsw = apsw.__main__:main

requirements:
  build:
    # - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - sqlite {{ version }}
  run:
    - python
    # Version through run_exports
    - sqlite

test:
  imports:
    - apsw
  requires:
    - pip
    - pytest
  commands:
    - pip check

about:
  home: https://github.com/rogerbinns/apsw
  license: any-OSI
  license_file: LICENSE
  license_family: OTHER
  summary: APSW stands for Another Python SQLite Wrapper.
  description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. It focuses translating between the complete SQLite C API and
    Python's C API. It is recommended to use the builtin sqlite3 module, unless
    you want SQLite specific functionality. The documentation has a section on
    the differences between APSW and sqlite3. APSW supports CPython 3.6
    onwards:
  doc_url: https://rogerbinns.github.io/apsw/pysqlite.html
  dev_url: https://github.com/rogerbinns/apsw

extra:
  recipe-maintainers:
    - stuertz
